config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :homes

      resources :furnitures

      resources :rooms

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "rooms#index"
  resources :homes
  resources :furnitures
  resources :rooms
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/furniture.rb
class Furniture < ApplicationRecord
  mount_base64_uploader :image, ImageUploader

  # Direct associations

  belongs_to :room

  # Indirect associations

  has_one    :home,
             through: :room,
             source: :home

  # Validations

  # Scopes

  def to_s
    room.to_s
  end
end

app/controllers/api/v1/furnitures_controller.rb
class Api::V1::FurnituresController < Api::V1::GraphitiController
  def index
    furnitures = FurnitureResource.all(params)
    respond_with(furnitures)
  end

  def show
    furniture = FurnitureResource.find(params)
    respond_with(furniture)
  end

  def create
    furniture = FurnitureResource.build(params)

    if furniture.save
      render jsonapi: furniture, status: :created
    else
      render jsonapi_errors: furniture
    end
  end

  def update
    furniture = FurnitureResource.find(params)

    if furniture.update_attributes
      render jsonapi: furniture
    else
      render jsonapi_errors: furniture
    end
  end

  def destroy
    furniture = FurnitureResource.find(params)

    if furniture.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: furniture
    end
  end
end

app/controllers/furnitures_controller.rb
class FurnituresController < ApplicationController
  before_action :set_furniture, only: %i[show edit update destroy]

  def index
    @q = Furniture.ransack(params[:q])
    @furnitures = @q.result(distinct: true).includes(:room,
                                                     :home).page(params[:page]).per(10)
  end

  def show; end

  def new
    @furniture = Furniture.new
  end

  def edit; end

  def create
    @furniture = Furniture.new(furniture_params)

    if @furniture.save
      message = "Furniture was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @furniture, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @furniture.update(furniture_params)
      redirect_to @furniture, notice: "Furniture was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @furniture.destroy
    message = "Furniture was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to furnitures_url, notice: message
    end
  end

  private

  def set_furniture
    @furniture = Furniture.find(params[:id])
  end

  def furniture_params
    params.require(:furniture).permit(:room_id, :image, :furniture_name)
  end
end

app/views/furnitures/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Furniture #<%= furniture.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Room</dt>
      <dd>
        <% if @furniture.room.present? %>
          <%= link_to furniture.room, furniture.room %>
        <% end %>
      </dd>

      <dt>Image</dt>
      <dd>
        <%= cl_image_tag @furniture.image, class: "img-fluid" %>
      </dd>

      <dt>Furniture name</dt>
      <dd><%= furniture.furniture_name %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back furniture, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_furniture_url(furniture), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to furniture, method: :delete, data: { confirm: "Do you really want to delete this furniture?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(furniture.updated_at) %> ago
  </div>
</div>

app/views/furnitures/_form.html.erb
<% was_validated = furniture.errors.any? %>

<%= form_with(model: furniture, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% room_class = "form-control" %>
    <% room_was_invalid = furniture.errors.include?(:room) %>

    <% if was_validated %>
      <% if room_was_invalid %>
        <% room_class << " is-invalid" %>
      <% else %>
        <% room_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :room_id %>
    <%= f.collection_select :room_id, Room.all, :id, :to_s, {}, class: "form-control" %>
    <% if room_was_invalid %>
      <% furniture.errors.full_messages_for(:room).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% image_class = "form-control" %>
    <% image_was_invalid = furniture.errors.include?(:image) %>

    <% if was_validated %>
      <% if image_was_invalid %>
        <% image_class << " is-invalid" %>
      <% else %>
        <% image_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
    <% if image_was_invalid %>
      <% furniture.errors.full_messages_for(:image).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% furniture_name_class = "form-control" %>
    <% furniture_name_was_invalid = furniture.errors.include?(:furniture_name) %>

    <% if was_validated %>
      <% if furniture_name_was_invalid %>
        <% furniture_name_class << " is-invalid" %>
      <% else %>
        <% furniture_name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :furniture_name %>
    <%= f.text_field :furniture_name, class: furniture_name_class, placeholder: "Enter furniture name" %>
    <% if furniture_name_was_invalid %>
      <% furniture.errors.full_messages_for(:furniture_name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/furnitures/_furniture_home.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Home
  </div>

  <ul class="list-group list-group-flush">
    <% @furniture.home.each do |home| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/homes/<%= home.id %>">
          <%= home %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/furnitures/_furnitures_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "furnitures_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :furniture_name_cont, "Furniture name contains" %>
    <%= f.text_field :furniture_name_cont, :class => "form-control", :placeholder => "Furniture name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :room_room_name_cont, "Room room_name contains" %>
    <%= f.text_field :room_room_name_cont, :class => "form-control", :placeholder => "Room room_name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :user_id, "Home User" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :home_user_id_gteq, :class => "form-control", :placeholder => "Home User greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :home_user_id_lteq, :class => "form-control", :placeholder => "Home User less than or equal to" %>
      </div>
    </div>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/furnitures" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#furnitures_filters">
  Show filters
</a>

app/views/furnitures/_list_item.html.erb
<%= link_to furniture, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= furniture %>
    <small class="text-muted">
      <%= time_ago_in_words(furniture.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/furnitures/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Furniture #<%= @furniture.id %>
      </h2>

      <div class="card-body">
        <%= render "form", furniture: @furniture %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/furnitures/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Furnitures

      <%= link_to new_furniture_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "furnitures/furnitures_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Furnitures

        <%= link_to new_furniture_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @furnitures, partial: "list_item", as: :furniture %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @furnitures, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/furnitures/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Furniture
      </h2>

      <div class="card-body">
        <%= render "form", furniture: @furniture %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/furnitures/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @furniture, partial: "card", as: :furniture %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "furnitures/furniture_home" %>
  </div>
</div>